"""comments

Revision ID: 1d56e8fdac0f
Revises: f3bfa9061c69
Create Date: 2018-06-28 21:10:10.794659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d56e8fdac0f'
down_revision = 'f3bfa9061c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    # ### end Alembic commands ###
